config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root "tweets#index"
  resources :tweets, only: [:index, :show, :new, :destroy, :edit, :update ,:create] do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  validates_presence_of :image, :text, :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :comments

  validates_uniqueness_of :nickname
  validates_presence_of :nickname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{@comment.tweet.id}"
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :jump_index, except: [:index]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end

  def new
    @tweet= Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.user_id == current_user.id
      @tweet.update(tweet_params)
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end

  def jump_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>blog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

  </head>

  <body>

  <div class="buttons are-medium">
    <% if user_signed_in? %>
      <a class="button is-primary" href="/users/<%= current_user.id %>">マイページ</a>
      <a class="button is-primary" href="/users/sign_out">ログアウト</a>
      <a class="button is-primary" href="/tweets/new">投稿する</a>
    <% else %> 
      <a class="button is-primary" href="/users/sign_in">ログイン</a>
      <a class="button is-primary" href="/users/sign_up">新規登録</a>
    <% end %>
  </div>

  <section class="hero is-primary">
    <div class="hero-body">
      <div class="container">
        <a href="/" class="title">blog</a>
      </div>
    </div>
  </section>

  <%= yield %>

  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="card">
    <div class="card-image">
      <figure class="image is-4by3" style="background-image: url(<%= tweet.image %>);"></figure>
    </div>
    <header class="card-header">
    <p class="card-header-title">
      みんブロ！ shared
    </p>
    <a href="#" class="card-header-icon" aria-label="more options">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </a>
  </header>
  <div class="card-content">
    <div class="content">
      <%= simple_format(tweet.text) %>
      <a href="#"><%= tweet.user.nickname %></a>
      <br>
      <time datetime="2016-1-1"><%= tweet.created_at %></time>
    </div>
  </div>
  <footer class="card-footer">
  <ul>
      <li>
        <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
      </li>
    <% if user_signed_in? && current_user.id == tweet.user_id %>
      <li>
        <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
      </li>
      <li>
        <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
      </li>
    <% end %>
    </ul>
  </footer>
</div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="button is-primary" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_for(@tweet) do |f| %>
      <h3>
        編集する
      </h3>
      <div class="field">
        <%= f.label :image %><br />
        <%= f.text_field :image, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :text %><br />
        <%= f.text_area :text, autofocus: true %>
      </div>
      <div class="actions">
        <%= f.submit "SENT" %>
      </div>
    <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents row" >
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet",locals:{tweet: tweet} %>
  <% end %>
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_for(@tweet) do |f| %>
      <h3>
        投稿する
      </h3>
      <div class="field">
        <%= f.label :image %><br />
        <%= f.text_field :image, autofocus: true %>
    </div>
      <div class="field">
        <%= f.label :text %><br />
        <%= f.text_area :text, autofocus: true %>
      </div>
      <div class="actions">
        <%= f.submit "SENT" %>
      </div>
  <% end %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if current_user && @tweet.user_id == current_user.id %>
      <div class="more">
      <ul class="more_list">
          <li>
            <%= link_to '削除', tweet_path(@tweet.id) %>
          </li>
      </ul>
      </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user_id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input class="button is-primary" type="submit" value="SENT">
      <% end %>
    <% end %>
    <div class="comments">
      <% if @comments %>
        <h4>＜コメント一覧＞</h4>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      編集が完了しました。
    </h3>
    <a class="button is-primary" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
 <div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @tweets.each do |tweet| %>
      <div class="content_post" style="background-image: url(<%= tweet.image %>);">
        <%= simple_format(tweet.text) %>
      </div>
    <% end %>
    <%= paginate(@tweets) %>
  </div>